spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/haein
    username: sa
    password: haein
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # system.out
        format_sql: true
        default_batch_fetch_size: 100 # in query(의 개수 설정)로 db에 있는 userA와 userB의 orderItems를 한 번에 가져온 것!

logging:
  level:
    org.hibernate.SQL: debug # log
#    org.hibernate.type: trace # query parameter
